

export const SHOP_NAME_EMPTY = 'SHOP_NAME_EMPTY';

export const SHOP_NAME_SUCCESS = 'SHOP_NAME_SUCCESS';


export const SHOP_NAME_CLEAR = 'SHOP_NAME_CLEAR';





export const LOGIN_REQ = 'LOGIN_REQ';
export const LOGIN_RESPONSE = 'LOGIN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const LOG_IN_FAIL = 'LOG_IN_FAIL';



export const PRODUCTLIST_ACTION="PRODUCTLIST_ACTION";
export const CATEGORY_LIST_REQ="CATEGORY_LIST_REQ";
export const CATEGORY_LIST_ACTION="CATEGORY_LIST_ACTION";

export const CATEGORY_LIST_ID="CATEGORY_LIST_ID";





export const PRODUCT_SEARCH_QUERY="PRODUCT_SEARCH_QUERY";
export const PRODUCT_SEARCH_EMPTY="PRODUCT_SEARCH_EMPTY";
export const CART_INC="CART_INC";
export const CART_DEC="CART_DEC";
export const CART_DELETE="CART_DELETE";
export const ALL_CATEGORY="ALL_CATEGORY";


export const MANUFACTURE_LIST_REQ="MANUFACTURE_LIST_REQ";
export const MANUFACTURE_LIST="MANUFACTURE_LIST";


export const TAX_LIST_REQ="TAX_LIST_REQ";
export const TAX_LIST="TAX_LIST";




export const GALLERY_IMG_VIEW="GALLERY_IMG_VIEW";
export const GALLERY_UPLOAD="GALLERY_UPLOAD";

export const  DELETEOPTION_REQUEST="DELETEOPTION_REQUEST";
export const  DELETEOPTION_SUCCESS="DELETEOPTION_SUCCESS";
export const  DELETEOPTION_FAIL="DELETEOPTION_FAIL";


export const  CUSTOMER_LIST_REQ="CUSTOMER_LIST_REQ";
export const  CUSTOMER_LIST_SUCCES="CUSTOMER_LIST_SUCCES";
export const  CUSTOMER_LIST_FAIL="CUSTOMER_LIST_FAIL";



export const  CUSTOMER_EDIT_REQ="CUSTOMER_EDIT_REQ"
export const  CUSTOMER_EDIT_SUCCES="CUSTOMER_EDIT_SUCCES"
export const  CUSTOMER_EDIT_FAIL="CUSTOMER_EDIT_FAIL"



export const  CUSTOMER_DELETE_REQ="CUSTOMER_DELETE_REQ";
export const  CUSTOMER_DELETE_SUCCES="CUSTOMER_DELETE_SUCCES";
export const  CUSTOMER_DELETE_FAIL="CUSTOMER_DELETE_FAIL";



export const  CART_ADD_REQSSS="CART_ADD_REQSSS";

export const  CART_EXISTS="CART_EXISTS";


export const CART_ADD="CART_ADD";

export const CART_VIEW="CART_VIEW";

export const CART_VIEW_FAIL="CART_VIEW_FAIL";



export const CART_CLEAR_REQ="CART_CLEAR_REQ";
export const CART_CLEAR="CART_CLEAR";






export const GET_SESSION_TOKEN="GET_SESSION_TOKEN";


export const GET_SESSION_CLEAR="GET_SESSION_CLEAR";


export const DR_VIEW_REQUEST ="DR_VIEW_REQUEST";

export const DR_VIEW_SUCCESS ="DR_VIEW_SUCCESS";

export const DR_VIEW_FAIL ="DR_VIEW_FAIL";



export const DR_OPEN__REQUEST ="DR_OPEN__REQUEST";

export const DR_OPEN_SUCCESS ="DR_OPEN_SUCCESS";

export const DR_OPEN_FAIL ="DR_OPEN_FAIL";



export const SINGLE_CAT_ID ="SINGLE_CAT_ID";





export const CATEGORY_WISE_PR_REQ ="CATEGORY_WISE_PR_REQ";
export const CATEGORY_WISE_PR_SUCCESS ="CATEGORY_WISE_PR_SUCCESS";
export const CATEGORY_WISE_PR_FAIL ="CATEGORY_WISE_PR_FAIL";


export const CUSTOMER_DATA ="CUSTOMER_DATA"



export const CANCEL_BILL_REQ ="CANCEL_BILL_REQ";
export const CANCEL_BILL_SUCCESS ="CANCEL_BILL_SUCCESS";
export const CANCEL_BILL_FAIL ="CANCEL_BILL_FAIL";
export const COD_ADD= "COD_ADD"



export const SETTING_REQ="SETTING_REQ"
export const SETTING_FAIL="SETTING_FAIL"
export const SETTING_SUCCESS="SETTING_SUCCESS"




export const CART_HOLD_REQ="CART_HOLD_REQ"

export const CART_HOLD_SUCCESS="CART_HOLD_SUCCESS"

export const CART_HOLD_FAIL="CART_HOLD_FAIL"



export const HOLD_LIST_REQ="HOLD_LIST_REQ"

export const HOLD_LIST_SUCCESS="HOLD_LIST_SUCCESS"

export const HOLD_LIST_FAIL="HOLD_LIST_FAIL"


export const CART_HOLD_DTREQ="CART_HOLD_DTREQ"

export const CART_HOLD_DTSUCCESS="CART_HOLD_DTSUCCESS"

export const CART_HOLD_DTFAIL="CART_HOLD_DTFAIL"




export const CART_HOLD_RETRIEV_REQ="CART_HOLD_RETRIEV_REQ"
export const CART_HOLD_RETRIEV_SUCCESS="CART_HOLD_RETRIEV_SUCCESS"
export const CART_HOLD_RETRIEV_FAIL="CART_HOLD_RETRIEV_FAIL"




export const SINGLE_PR_DELETE_REQ="SINGLE_PR_DELETE_REQ"
export const SINGLE_PR_DELETE_SUCCESS="SINGLE_PR_DELETE_SUCCESS"
export const SINGLE_PR_DELETE_FAIL="SINGLE_PR_DELETE_FAIL"


export const POS_ADMIN_REQ="POS_ADMIN_REQ"
export const POS_ADMIN_SUCCESS="POS_ADMIN_SUCCESS"
export const POS_ADMIN_FAIL="POS_ADMIN_FAIL"





export const LANGUAGE_REQ="LANGUAGE_REQ"
export const LANGUAGE_SUCCESS="LANGUAGE_SUCCESS"
export const LANGUAGE_FAIL="LANGUAGE_FAIL"
export const SELECT_LANGUAGE="SELECT_LANGUAGE"


export const CURRENCY_REQ="CURRENCY_REQ"
export const CURRENCY_SUCCESS="CURRENCY_SUCCESS"
export const CURRENCY_FAIL="CURRENCY_FAIL"
export const SELECT_CURRENCY="SELECT_CURRENCY"






export const RETRIEV_DEL_REQ ="RETRIEV_DEL_REQ"

export const RETRIEV_DEL_SUCCESS ="RETRIEV_DEL_SUCCESS"





export const COUPON_ADD_REQ ="COUPON_ADD_REQ"
export const COUPON_ADD_SUCCESS ="COUPON_ADD_SUCCESS"
export const COUPON_RES_FAIL ="COUPON_RES_FAIL"



export const PURCHASE_LIST_REQ ="PURCHASE_LIST_REQ"
export const PURCHASE_LIST_SUCCESS ="PURCHASE_LIST_SUCCESS"
export const PURCHASE_LIST_FAIL ="PURCHASE_LIST_FAIL"

export const OPTION_LIST_REQ ="OPTION_LIST_REQ"
export const OPTION_LIST_SUCCESS ="OPTION_LIST_SUCCESS"
export const OPTION_LIST_FAIL ="OPTION_LIST_FAIL"



export const GUEST_USER_REQ ="GUEST_USER_REQ"
export const GUEST_USER_SUCCESS ="GUEST_USER_SUCCESS"
export const GUEST_USER_FAIL ="GUEST_USER_FAIL"





